# Use a consistent test timezone
ENV["TZ"] = "UTC"

# Only load and start SimpleCov if we are actually running specs. RSpec loads
# this file when it runs as part of the Rails model generator - we don't want to
# load coverage in a generator because coverage will fail and prevent the
# generator from completing.
if RSpec.configuration.files_to_run.length > 1
  require "simplecov"
  require "simplecov-lcov"

  SimpleCov::Formatter::LcovFormatter.config do |c|
    c.report_with_single_file = true
    c.single_report_path = 'coverage/lcov.info'
  end

  SimpleCov.formatters = [
    SimpleCov::Formatter::HTMLFormatter,
    SimpleCov::Formatter::LcovFormatter
  ]

  # Configure minimum test coverage levels
  SimpleCov.start("rails") do
    enable_coverage :branch

    use_merging false

    # Enhanced coverage thresholds - standardized across all projects
    minimum_coverage line: 75, branch: 50
    minimum_coverage_by_file 50

    # Enhanced grouping for better reporting
    add_group 'Controllers', 'app/controllers'
    add_group 'Models', 'app/models'
    add_group 'Services', 'app/services'
    add_group 'Helpers', 'app/helpers'
    add_group 'Components', 'app/components'
    add_group 'Policies', 'app/policies'
    add_group 'Jobs', 'app/jobs'
    add_group 'Mailers', 'app/mailers'
    add_group 'Libraries', 'lib'

    add_filter "/bin/"
    add_filter "/spec/"
    add_filter "/config/"
    add_filter "/db/"
    add_filter "/vendor/"
    add_filter "/tmp/"
    add_filter "/log/"
    add_filter "/public/"
    add_filter "/storage/"
    add_filter "/node_modules/"
    add_filter "/lib/tasks/"

    # Exclude base/abstract classes
    add_filter 'app/controllers/application_controller.rb'
    add_filter 'app/models/application_record.rb'
    add_filter 'app/jobs/application_job.rb'
    add_filter 'app/mailers/application_mailer.rb'
    add_filter 'app/channels/application_cable/'

    # Custom tiered coverage criteria
    coverage_criteria = {
      primary: 90,    # Models, Controllers, Services
      secondary: 80,  # Helpers, Components, Policies
      tertiary: 70    # Jobs, Mailers
    }

    # Report coverage by tier
    at_exit do
      result = SimpleCov.result

      # Check coverage by group
      primary_groups = [ 'Controllers', 'Models', 'Services' ]
      secondary_groups = [ 'Helpers', 'Components', 'Policies' ]
      tertiary_groups = [ 'Jobs', 'Mailers' ]

      primary_files = result.files.select { |f| primary_groups.any? { |g| f.filename.include?(g.downcase) } }
      secondary_files = result.files.select { |f| secondary_groups.any? { |g| f.filename.include?(g.downcase) } }

      if primary_files.any? && primary_files.map(&:covered_percent).sum / primary_files.size < coverage_criteria[:primary]
        puts "\n[COVERAGE] Primary code coverage below #{coverage_criteria[:primary]}%"
        puts "   Focus on: Controllers, Models, Services"
      end

      if secondary_files.any? && secondary_files.map(&:covered_percent).sum / secondary_files.size < coverage_criteria[:secondary]
        puts "\n[COVERAGE] Secondary code coverage below #{coverage_criteria[:secondary]}%"
        puts "   Focus on: Helpers, Components, Policies"
      end

      if result.covered_percent >= 90
        puts "\n[COVERAGE] Excellent test coverage: #{result.covered_percent.round(2)}%"
      elsif result.covered_percent >= 75
        puts "\n[COVERAGE] Good test coverage: #{result.covered_percent.round(2)}%"
      else
        puts "\n[COVERAGE] Test coverage needs improvement: #{result.covered_percent.round(2)}%"
      end
    end
  end
end

# This file was generated by the `rails generate rspec:install` command.
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups

  # The --only-failures option filters what examples are run
  config.example_status_persistence_file_path = "tmp/rspec_example_status_persistence_file.txt"
end
